name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch: # Ti permette di farlo partire a comando dalla tab Actions

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Set up Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build Release APK
      run: ./gradlew assembleRelease

    - name: Sign APK
      uses: r0adkll/sign-android-release@v1
      id: sign_app
      with:
        releaseDirectory: app/build/outputs/apk/release
        signingKeyBase64: ${{ secrets.KEYSTORE }}
        alias: ${{ secrets.KEY_ALIAS }}
        keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
        keyPassword: ${{ secrets.KEY_PASSWORD }}
      env:
        BUILD_TOOLS_VERSION: "34.0.0"

    - name: Rename Signed APK
      run: mv ${{ steps.sign_app.outputs.signedReleaseFile }} app/build/outputs/apk/release/Smart-register.apk

    - name: Create Release
      uses: softprops/action-gh-release@v1
      if: github.event_name != 'pull_request'
      with:
        tag_name: latest-build
        name: "Smart-register"
        body: |
          🚀 **Latest signed build created successfully**
          This apk is ready and signed.
        draft: false
        prerelease: false
        # Carica solo il file rinominato, ignorando quelli "unsigned"
        files: app/build/outputs/apk/release/PhotoTinder.apk
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
